name: Fuzz Nightly

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  fuzz-nightly:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
      RUSTFLAGS: '-Ctarget-cpu=native'
    strategy:
      matrix:
        fuzz_target: [token-swap-instructions]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Set up Solana
        run: |
          source ci/rust-version.sh
          echo "RUST_STABLE=$rust_stable" >> $GITHUB_ENV
          source ci/solana-version.sh
          echo "SOLANA_VERSION=$solana_version" >> $GITHUB_ENV
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Cache Cargo dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache fuzzing binaries
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/cargo-hfuzz
            ~/.cargo/bin/cargo-honggfuzz
          key: ${{ runner.os }}-fuzz-bins

      - name: Cache Solana CLI
        uses: actions/cache@v2
        with:
          path: ~/.cache/solana
          key: ${{ runner.os }}-solana-${{ env.SOLANA_VERSION }}
          restore-keys: |
            ${{ runner.os }}-solana-

      - name: Install dependencies
        run: |
          ./ci/install-build-deps.sh
          ./ci/install-program-deps.sh

      - name: Run fuzz target
        run: ./ci/fuzz.sh ${{ matrix.fuzz_target }} 18000 # 5 hours, jobs max out at 6
